version: '2'
services: 
 
 api:
  build: 
    context: ..
    dockerfile: containerization/Dockerfile.webapp
  volumes:
    - ../:/container/app
  ports:
    - 8080:8080
    - 8443:8443
  entrypoint: ["/bin/bash", "-c", "npm run dev:serve" ]
