FROM node:lts

WORKDIR /container
RUN mkdir -p app/node_modules
RUN mkdir -p app/webapp/dist
RUN chown -R node /container
USER node
WORKDIR /container/app
COPY --chown=node:node ./package.json ./
COPY --chown=node:node ./tsconfig.json ./
COPY --chown=node:node ./webapp/ ./webapp/
RUN npm install
ENTRYPOINT ["/bin/bash", "-c", "npm run build"]
